-- Schema baseline for kafkatower-common's own tables (PostgreSQL — production).
-- Applied on fresh installs. Set baseline-on-migrate=false when running against a new DB.

CREATE TABLE IF NOT EXISTS chat_feedback (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   VARCHAR(255) NOT NULL,
    user_id      VARCHAR(255) NOT NULL,
    user_prompt  TEXT         NOT NULL,
    agent_answer TEXT         NOT NULL,
    feedback     VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL
);

CREATE TABLE IF NOT EXISTS prompt_analytics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMPTZ  NOT NULL,
    user_id      VARCHAR(255),
    theme        VARCHAR(255) NOT NULL,
    keywords     VARCHAR(255),
    agent_routed VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS llm_settings (
    id       BIGINT       PRIMARY KEY,
    api_key  VARCHAR(1000),
    base_url VARCHAR(500),
    model    VARCHAR(255)
);
