-- Schema baseline for kafkatower-common's own tables (H2 — dev / test).
-- Applied on fresh installs. Existing instances use baseline-on-migrate=true to skip this.

CREATE TABLE IF NOT EXISTS chat_feedback (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id   VARCHAR(255) NOT NULL,
    user_id      VARCHAR(255) NOT NULL,
    user_prompt  CLOB         NOT NULL,
    agent_answer CLOB         NOT NULL,
    feedback     VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS prompt_analytics (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP    NOT NULL,
    user_id      VARCHAR(255),
    theme        VARCHAR(255) NOT NULL,
    keywords     VARCHAR(255),
    agent_routed VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS llm_settings (
    id       BIGINT       PRIMARY KEY,
    api_key  VARCHAR(1000),
    base_url VARCHAR(500),
    model    VARCHAR(255)
);
